services:
  dind:
    image: my-dind
    build: .
    privileged: true
    command:
      - --insecure-registry
      - registry:5000
    volumes:
      - .:/work
    networks:
      default:
        ipv4_address: 172.16.100.10

  registry:
    image: registry:2
    networks:
      default:
        ipv4_address: 172.16.100.11

networks:
  default:
    ipam:
     config:
       - subnet: 172.16.100.0/24
